Multi-sample text neuron activations
alan-cooney/CircuitsVis pull request #34
Opened 2022-12-19 17:10 UTC by danbraunai

Allows for showing multiple samples in the TextNeuronActivations vis, with pagination via select:
<img width="972" alt="image" src="https://user-images.githubusercontent.com/26232738/208480835-535451ee-e304-4d76-ac08-f34bfe882f84.png">

(Note, this PR uses functionality introduced in the [topk PR](https://github.com/alan-cooney/CircuitsVis/pull/21). All topk commits are included here, but it would be cleaner to merge the topk PR first.)

2022-12-23 10:20 UTC, danbraunai commented
TODO: Put the colours from each sample in the whole dataset on the same scale. Currently each sample gets its own colour scale, which can be confusing when viewing activations across samples.

2022-12-30 14:55 UTC, alan-cooney requested changes
Sorry about the delay on this!

Generally looks good - are you able to fix the merge conflicts on your branch and then I'll merge in?

2023-01-03 20:52 UTC, alan-cooney approved these changes

2023-01-03 20:53 UTC, merged

2023-01-03 20:53 UTC, alan-cooney commented
Thanks for the PR!