Log Prob Visualiser
alan-cooney/CircuitsVis pull request #36
Opened 2022-12-24 02:54 UTC by neelnanda-io

Added a log prob visualizer! This shows you some text, with tokens coloured by the log prob of the model. If you hover over a token, it shows you the top 10 tokens predicted, along with logits and log probs, and the values + rank of the correct token. The correct token is highlighted in the list of top 10 if it occurs in there (if so, it appears twice).

![image](https://user-images.githubusercontent.com/77788841/209418803-ac23ed13-fed3-47fe-b57c-d4d7bd092715.png)

![image](https://user-images.githubusercontent.com/77788841/209418807-1cb95f00-757c-43c6-8184-3b26550716fc.png)

2022-12-24 02:55 UTC, neelnanda-io commented
Did some internal refactoring of the Token class - pulled out the formatting text part into a separate function, and added a `TokenCustomTooltip` class that can display an arbitrary React Component as its tooltip.

I also have some local code that automates the creation of BS boilerplate (for writing the visualization and for mocking)

2022-12-30 15:01 UTC, alan-cooney requested changes
A few small changes in the comments - note the checks are also failing so there may be an issue still after these are made

2022-12-30 15:39 UTC, neelnanda-io commented on react/src/repl_tf.js
> +    try {
Oh lol, nope.

2022-12-30 15:40 UTC, neelnanda-io commented
Not sure how the dependency changes happened!

2022-12-30 15:45 UTC, neelnanda-io commented
All changes made

2022-12-30 16:03 UTC, neelnanda-io commented
I did not notice that there were tests! Turns out I had an actual bug, so good shout (imported some things twice in index.ts), fixed.
Also funky, my local code thought the library was v 1.6.0 not 1.34.0, which broke the topk test. I added a thing which monkey patches the version to avoid each update breaking this, but happy to revert if you want. It _did_ catch a real bug in my case, but will also break for each new version.

2023-01-07 21:28 UTC, merged